# 直接放行URL
security:
  oauth2:
    ignore:
      urls:
        - /v2/api-docs
        - /actuator/**
        - /test/**
        - /info/**
spring:
  cache:
    type: redis
  main:
    allow-bean-definition-overriding: true
