### Application Pod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pig-xxl-job-admin
  namespace: data-middle-platform
  labels:
    app: pig-xxl-job-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pig-xxl-job-admin
  template:
    metadata:
      labels:
        app: pig-xxl-job-admin
    spec:
      containers:
        - name: pig-xxl-job-admin
          image: "dockerhub.clinbrain.com/pig-xxl-job-admin:20220125_528632b3"
          imagePullPolicy: Always
          env:
            - name: NACOS_HOST
              value: 192.168.0.112
            - name: NACOS_PORT
              value: "8848"
            - name: pig-register
              value: "192.168.0.112"
            - name: pig-mysql
              value: "192.168.0.112"
            - name: pig-redis
              value: "192.168.0.112"

          volumeMounts:
            - name: config-volume
              mountPath: /home/java/application.properties
              subPath: application.properties
            - name: config-volume
              mountPath: /home/java/application-kubernetes.properties
              subPath: application-kubernetes.properties
      nodeSelector:
        flag-pig-xxl-job-admin: enabled
      volumes:
        - name: config-volume
          configMap:
            name: pig-xxl-job-admin-config

### Application Service
---
apiVersion: v1
kind: Service
metadata:
  name: pig-xxl-job-admin
  namespace: data-middle-platform
spec:
  type: NodePort
  ports:
    - port: 14034
      nodePort: 14034
      targetPort: 8080
  selector:
    app: pig-xxl-job-admin

### Application Config MAP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pig-xxl-job-admin-config
  namespace: data-middle-platform
data:
  bootstrap.yml: |
    # 此配置只适合开发测试环境，详细配置参考： http://t.cn/A64RaHJm
    server:
      port: 5004
      servlet:
        context-path: /xxl-job-admin

    spring:
      application:
        name: @artifactId@
      cloud:
        nacos:
          discovery:
            server-addr: ${NACOS_HOST:pig-register}:${NACOS_PORT:8848}
            metadata:
              management.context-path: ${server.servlet.context-path}/actuator
      profiles:
        active: @profiles.active@

  application.yml: |
    # xxl
    xxl:
      job:
        i18n: zh_CN
        logretentiondays: 30
        triggerpool:
          fast.max: 200
          slow.max: 200

    # mybatis
    mybatis:
      mapper-locations: classpath:/mybatis-mapper/*Mapper.xml

    # spring
    spring:
      datasource:
        url: jdbc:mysql://${MYSQL_HOST:pig-mysql}:${MYSQL_PORT:3306}/${MYSQL_DB:pig_job}?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: ${MYSQL_USER:root}
        password: ${MYSQL_PWD:root}
      mvc:
        static-path-pattern: /static/**
      freemarker:
        suffix: .ftl
        request-context-attribute: request
        settings:
          number_format: 0.##########
      mail:
        host: smtp.mxhichina.com
        port: 465
        from: xxxx@gitee.wang
        username: xxxx@gitee.wang
        password: xxxx
        properties:
          mail:
            smtp:
              auth: true
              ssl.enable: true
              starttls.enable: false
              required: false
    # spring boot admin 配置

    management:
      health:
        mail:
          enabled: false
      endpoints:
        web:
          exposure:
            include: '*'
      endpoint:
        health:
          show-details: ALWAYS


  logback-spring.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <configuration debug="false" scan="false">
    	<springProperty scop="context" name="spring.application.name" source="spring.application.name" defaultValue=""/>
    	<property name="log.path" value="logs/${spring.application.name}"/>
    	<!-- 彩色日志格式 -->
    	<property name="CONSOLE_LOG_PATTERN"
    			  value="${CONSOLE_LOG_PATTERN:-%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}}"/>
    	<!-- 彩色日志依赖的渲染类 -->
    	<conversionRule conversionWord="clr" converterClass="org.springframework.boot.logging.logback.ColorConverter"/>
    	<conversionRule conversionWord="wex"
    					converterClass="org.springframework.boot.logging.logback.WhitespaceThrowableProxyConverter"/>
    	<conversionRule conversionWord="wEx"
    					converterClass="org.springframework.boot.logging.logback.ExtendedWhitespaceThrowableProxyConverter"/>
    	<!-- Console log output -->
    	<appender name="console" class="ch.qos.logback.core.ConsoleAppender">
    		<encoder>
    			<pattern>${CONSOLE_LOG_PATTERN}</pattern>
    		</encoder>
    	</appender>

    	<!-- Log file debug output -->
    	<appender name="debug" class="ch.qos.logback.core.rolling.RollingFileAppender">
    		<file>${log.path}/debug.log</file>
    		<rollingPolicy class="ch.qos.logback.core.rolling.SizeAndTimeBasedRollingPolicy">
    			<fileNamePattern>${log.path}/%d{yyyy-MM, aux}/debug.%d{yyyy-MM-dd}.%i.log.gz</fileNamePattern>
    			<maxFileSize>50MB</maxFileSize>
    			<maxHistory>30</maxHistory>
    		</rollingPolicy>
    		<encoder>
    			<pattern>%date [%thread] %-5level [%logger{50}] %file:%line - %msg%n</pattern>
    		</encoder>
    	</appender>

    	<!-- Log file error output -->
    	<appender name="error" class="ch.qos.logback.core.rolling.RollingFileAppender">
    		<file>${log.path}/error.log</file>
    		<rollingPolicy class="ch.qos.logback.core.rolling.SizeAndTimeBasedRollingPolicy">
    			<fileNamePattern>${log.path}/%d{yyyy-MM}/error.%d{yyyy-MM-dd}.%i.log.gz</fileNamePattern>
    			<maxFileSize>50MB</maxFileSize>
    			<maxHistory>30</maxHistory>
    		</rollingPolicy>
    		<encoder>
    			<pattern>%date [%thread] %-5level [%logger{50}] %file:%line - %msg%n</pattern>
    		</encoder>
    		<filter class="ch.qos.logback.classic.filter.ThresholdFilter">
    			<level>ERROR</level>
    		</filter>
    	</appender>

    	<!--nacos 心跳 INFO 屏蔽-->
    	<logger name="com.alibaba.nacos" level="OFF">
    		<appender-ref ref="error"/>
    	</logger>

    	<!-- Level: FATAL 0  ERROR 3  WARN 4  INFO 6  DEBUG 7 -->
    	<root level="INFO">
    		<appender-ref ref="console"/>
    		<appender-ref ref="debug"/>
    		<appender-ref ref="error"/>
    	</root>
    </configuration>




### Application Authority Role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: data-middle-platform
  name: pig-xxl-job-admin-reader
rules:
  - apiGroups: [""]
    resources: ["pods","configmaps","services"]
    verbs: ["get", "watch", "list"]
### Application Authority Role  Ref
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pig-xxl-job-admin-reader
  namespace: data-middle-platform
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pig-xxl-job-admin-reader
subjects:
  - kind: ServiceAccount
    name: default
    namespace: data-middle-platform
### Application Read Config Map Default ServiceAccount
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: data-middle-platform
